### ISSUE TITLE
When deploying in Odoo SH the addon of the branch 16 to 18-09-2023, shows errors with requirements.txt

### ISSUE THREAD

**Issue by Saurat** [ingadhoc/website#255]
The message that show to me is: 

Retrying with new resolver: /usr/local/bin/pip3 install --user --log=/home/odoo/logs/pip.log -r /home/odoo/.requirements.txt
2023-09-18T18:51:03,672 Using pip 23.2.1 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)
2023-09-18T18:51:03,672 User install by explicit request
2023-09-18T18:51:03,829 Created temporary directory: /tmp/pip-build-tracker-ymkimtw4
2023-09-18T18:51:03,830 Initialized build tracking at /tmp/pip-build-tracker-ymkimtw4
2023-09-18T18:51:03,830 Created build tracker: /tmp/pip-build-tracker-ymkimtw4
2023-09-18T18:51:03,830 Entered build tracker: /tmp/pip-build-tracker-ymkimtw4
2023-09-18T18:51:03,830 Created temporary directory: /tmp/pip-install-cdo5mku5
2023-09-18T18:51:03,834 Created temporary directory: /tmp/pip-ephem-wheel-cache-0hygf0n3
2023-09-18T18:51:03,848 Collecting git+https://github.com/pysimplesoap/pysimplesoap@a330d9c4af1b007fe1436f979ff0b9f66613136e (from -r /home/odoo/.requirements.txt (line 5))
2023-09-18T18:51:03,849   Created temporary directory: /tmp/pip-req-build-51sir7o7
2023-09-18T18:51:03,849   Cloning https://github.com/pysimplesoap/pysimplesoap (to revision a330d9c4af1b007fe1436f979ff0b9f66613136e) to /tmp/pip-req-build-51sir7o7
2023-09-18T18:51:03,850   Running command git version
2023-09-18T18:51:03,852   git version 2.34.1
2023-09-18T18:51:03,852   Running command git clone --filter=blob:none --quiet https://github.com/pysimplesoap/pysimplesoap /tmp/pip-req-build-51sir7o7
2023-09-18T18:51:04,616   Running command git show-ref a330d9c4af1b007fe1436f979ff0b9f66613136e
2023-09-18T18:51:04,618   Running command git rev-parse -q --verify 'sha^a330d9c4af1b007fe1436f979ff0b9f66613136e'
2023-09-18T18:51:04,621   Running command git fetch -q https://github.com/pysimplesoap/pysimplesoap a330d9c4af1b007fe1436f979ff0b9f66613136e
2023-09-18T18:51:04,891   Running command git rev-parse FETCH_HEAD
2023-09-18T18:51:04,893   a330d9c4af1b007fe1436f979ff0b9f66613136e
2023-09-18T18:51:04,893   Rev options <RevOptions git: rev='a330d9c4af1b007fe1436f979ff0b9f66613136e'>, branch_name None
2023-09-18T18:51:04,894   Running command git rev-parse HEAD
2023-09-18T18:51:04,895   ad03a21cafab982eed321553c4bfcda1755182eb
2023-09-18T18:51:04,896   Running command git checkout -q a330d9c4af1b007fe1436f979ff0b9f66613136e
2023-09-18T18:51:05,211   Resolved https://github.com/pysimplesoap/pysimplesoap to commit a330d9c4af1b007fe1436f979ff0b9f66613136e
2023-09-18T18:51:05,212   Running command git rev-parse HEAD
2023-09-18T18:51:05,215   a330d9c4af1b007fe1436f979ff0b9f66613136e
2023-09-18T18:51:05,215   Added git+https://github.com/pysimplesoap/pysimplesoap@a330d9c4af1b007fe1436f979ff0b9f66613136e (from -r /home/odoo/.requirements.txt (line 5)) to build tracker '/tmp/pip-build-tracker-ymkimtw4'
2023-09-18T18:51:05,216   Running setup.py (path:/tmp/pip-req-build-51sir7o7/setup.py) egg_info for package from git+https://github.com/pysimplesoap/pysimplesoap@a330d9c4af1b007fe1436f979ff0b9f66613136e
2023-09-18T18:51:05,216   Created temporary directory: /tmp/pip-pip-egg-info-g9_yaaav
2023-09-18T18:51:05,216   Preparing metadata (setup.py): started
2023-09-18T18:51:05,217   Running command python setup.py egg_info
2023-09-18T18:51:05,496   /usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'console'
2023-09-18T18:51:05,496     warnings.warn(msg)
2023-09-18T18:51:05,497   /usr/lib/python3/dist-packages/setuptools/dist.py:493: UserWarning: Normalizing '1.08.14' to '1.8.14'
2023-09-18T18:51:05,497     warnings.warn(tmpl.format(**locals()))
2023-09-18T18:51:05,500   running egg_info
2023-09-18T18:51:05,501   creating /tmp/pip-pip-egg-info-g9_yaaav/PySimpleSOAP.egg-info
2023-09-18T18:51:05,501   writing /tmp/pip-pip-egg-info-g9_yaaav/PySimpleSOAP.egg-info/PKG-INFO
2023-09-18T18:51:05,501   writing dependency_links to /tmp/pip-pip-egg-info-g9_yaaav/PySimpleSOAP.egg-info/dependency_links.txt
2023-09-18T18:51:05,501   writing top-level names to /tmp/pip-pip-egg-info-g9_yaaav/PySimpleSOAP.egg-info/top_level.txt
2023-09-18T18:51:05,503   writing manifest file '/tmp/pip-pip-egg-info-g9_yaaav/PySimpleSOAP.egg-info/SOURCES.txt'
2023-09-18T18:51:05,505   reading manifest file '/tmp/pip-pip-egg-info-g9_yaaav/PySimpleSOAP.egg-info/SOURCES.txt'
2023-09-18T18:51:05,505   writing manifest file '/tmp/pip-pip-egg-info-g9_yaaav/PySimpleSOAP.egg-info/SOURCES.txt'
2023-09-18T18:51:05,543   Preparing metadata (setup.py): finished with status 'done'
2023-09-18T18:51:05,545   Source in /tmp/pip-req-build-51sir7o7 has version 1.8.14, which satisfies requirement PySimpleSOAP==1.8.14 from git+https://github.com/pysimplesoap/pysimplesoap@a330d9c4af1b007fe1436f979ff0b9f66613136e (from -r /home/odoo/.requirements.txt (line 5))
2023-09-18T18:51:05,545   Removed PySimpleSOAP==1.8.14 from git+https://github.com/pysimplesoap/pysimplesoap@a330d9c4af1b007fe1436f979ff0b9f66613136e (from -r /home/odoo/.requirements.txt (line 5)) from build tracker '/tmp/pip-build-tracker-ymkimtw4'
2023-09-18T18:51:05,553 Collecting git+https://github.com/ingadhoc/pyafipws@py3k (from -r /home/odoo/.requirements.txt (line 6))
2023-09-18T18:51:05,554   Created temporary directory: /tmp/pip-req-build-a9nfm0qc
2023-09-18T18:51:05,554   Cloning https://github.com/ingadhoc/pyafipws (to revision py3k) to /tmp/pip-req-build-a9nfm0qc
2023-09-18T18:51:05,554   Running command git version
2023-09-18T18:51:05,556   git version 2.34.1
2023-09-18T18:51:05,556   Running command git clone --filter=blob:none --quiet https://github.com/ingadhoc/pyafipws /tmp/pip-req-build-a9nfm0qc
2023-09-18T18:51:06,610   Running command git show-ref py3k
2023-09-18T18:51:06,612   227b57d69659e81a229da235f051071d446ce4f1 refs/remotes/origin/py3k
2023-09-18T18:51:06,612   Rev options <RevOptions git: rev='227b57d69659e81a229da235f051071d446ce4f1'>, branch_name py3k
2023-09-18T18:51:06,612   Running command git symbolic-ref -q HEAD
2023-09-18T18:51:06,614   refs/heads/master
2023-09-18T18:51:06,615   Running command git checkout -b py3k --track origin/py3k
2023-09-18T18:51:07,266   Switched to a new branch 'py3k'
2023-09-18T18:51:07,267 Branch 'py3k' set up to track remote branch 'py3k' from 'origin'.
2023-09-18T18:51:07,267   Resolved https://github.com/ingadhoc/pyafipws to commit 227b57d69659e81a229da235f051071d446ce4f1
2023-09-18T18:51:07,268   Running command git rev-parse HEAD
2023-09-18T18:51:07,270   227b57d69659e81a229da235f051071d446ce4f1
2023-09-18T18:51:07,271   Added git+https://github.com/ingadhoc/pyafipws@py3k (from -r /home/odoo/.requirements.txt (line 6)) to build tracker '/tmp/pip-build-tracker-ymkimtw4'
2023-09-18T18:51:07,271   Running setup.py (path:/tmp/pip-req-build-a9nfm0qc/setup.py) egg_info for package from git+https://github.com/ingadhoc/pyafipws@py3k
2023-09-18T18:51:07,272   Created temporary directory: /tmp/pip-pip-egg-info-l5lk2vy7
2023-09-18T18:51:07,272   Preparing metadata (setup.py): started
2023-09-18T18:51:07,272   Running command python setup.py egg_info
2023-09-18T18:51:07,495   running egg_info
2023-09-18T18:51:07,495   creating /tmp/pip-pip-egg-info-l5lk2vy7/PyAfipWs.egg-info
2023-09-18T18:51:07,496   writing /tmp/pip-pip-egg-info-l5lk2vy7/PyAfipWs.egg-info/PKG-INFO
2023-09-18T18:51:07,496   writing dependency_links to /tmp/pip-pip-egg-info-l5lk2vy7/PyAfipWs.egg-info/dependency_links.txt
2023-09-18T18:51:07,496   writing top-level names to /tmp/pip-pip-egg-info-l5lk2vy7/PyAfipWs.egg-info/top_level.txt
2023-09-18T18:51:07,498   writing manifest file '/tmp/pip-pip-egg-info-l5lk2vy7/PyAfipWs.egg-info/SOURCES.txt'
2023-09-18T18:51:07,500   reading manifest file '/tmp/pip-pip-egg-info-l5lk2vy7/PyAfipWs.egg-info/SOURCES.txt'
2023-09-18T18:51:07,500   adding license file 'LICENSE'
2023-09-18T18:51:07,501   writing manifest file '/tmp/pip-pip-egg-info-l5lk2vy7/PyAfipWs.egg-info/SOURCES.txt'
2023-09-18T18:51:07,528   Preparing metadata (setup.py): finished with status 'done'
2023-09-18T18:51:07,530   Source in /tmp/pip-req-build-a9nfm0qc has version 3.10.0, which satisfies requirement PyAfipWs==3.10.0 from git+https://github.com/ingadhoc/pyafipws@py3k (from -r /home/odoo/.requirements.txt (line 6))
2023-09-18T18:51:07,531   Removed PyAfipWs==3.10.0 from git+https://github.com/ingadhoc/pyafipws@py3k (from -r /home/odoo/.requirements.txt (line 6)) from build tracker '/tmp/pip-build-tracker-ymkimtw4'
2023-09-18T18:51:07,540 Collecting git+https://github.com/OCA/openupgradelib/@master (from -r /home/odoo/.requirements.txt (line 7))
2023-09-18T18:51:07,541   Created temporary directory: /tmp/pip-req-build-f8can7w8
2023-09-18T18:51:07,541   Cloning https://github.com/OCA/openupgradelib/ (to revision master) to /tmp/pip-req-build-f8can7w8
2023-09-18T18:51:07,542   Running command git version
2023-09-18T18:51:07,544   git version 2.34.1
2023-09-18T18:51:07,544   Running command git clone --filter=blob:none --quiet https://github.com/OCA/openupgradelib/ /tmp/pip-req-build-f8can7w8
2023-09-18T18:51:08,597   Running command git show-ref master
2023-09-18T18:51:08,600   d0aee908031876a95dc36c7a9a2c847186155aa2 refs/heads/master
2023-09-18T18:51:08,600   d0aee908031876a95dc36c7a9a2c847186155aa2 refs/remotes/origin/master
2023-09-18T18:51:08,600   Rev options <RevOptions git: rev='d0aee908031876a95dc36c7a9a2c847186155aa2'>, branch_name master
2023-09-18T18:51:08,600   Running command git symbolic-ref -q HEAD
2023-09-18T18:51:08,603   refs/heads/master
2023-09-18T18:51:08,603   Resolved https://github.com/OCA/openupgradelib/ to commit d0aee908031876a95dc36c7a9a2c847186155aa2
2023-09-18T18:51:08,604   Running command git rev-parse HEAD
2023-09-18T18:51:08,606   d0aee908031876a95dc36c7a9a2c847186155aa2
2023-09-18T18:51:08,606   Added git+https://github.com/OCA/openupgradelib/@master (from -r /home/odoo/.requirements.txt (line 7)) to build tracker '/tmp/pip-build-tracker-ymkimtw4'
2023-09-18T18:51:08,606   Running setup.py (path:/tmp/pip-req-build-f8can7w8/setup.py) egg_info for package from git+https://github.com/OCA/openupgradelib/@master
2023-09-18T18:51:08,607   Created temporary directory: /tmp/pip-pip-egg-info-87lpi6um
2023-09-18T18:51:08,607   Preparing metadata (setup.py): started
2023-09-18T18:51:08,607   Running command python setup.py egg_info
2023-09-18T18:51:08,858   /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: -VERSION- is an invalid version and will not be supported in a future release
2023-09-18T18:51:08,858     warnings.warn(
2023-09-18T18:51:08,861   /usr/lib/python3/dist-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
2023-09-18T18:51:08,862     warnings.warn(
2023-09-18T18:51:11,447   running egg_info
2023-09-18T18:51:11,448   creating /tmp/pip-pip-egg-info-87lpi6um/openupgradelib.egg-info
2023-09-18T18:51:11,448   writing /tmp/pip-pip-egg-info-87lpi6um/openupgradelib.egg-info/PKG-INFO
2023-09-18T18:51:11,448   writing dependency_links to /tmp/pip-pip-egg-info-87lpi6um/openupgradelib.egg-info/dependency_links.txt
2023-09-18T18:51:11,448   writing requirements to /tmp/pip-pip-egg-info-87lpi6um/openupgradelib.egg-info/requires.txt
2023-09-18T18:51:11,448   writing top-level names to /tmp/pip-pip-egg-info-87lpi6um/openupgradelib.egg-info/top_level.txt
2023-09-18T18:51:11,450   writing manifest file '/tmp/pip-pip-egg-info-87lpi6um/openupgradelib.egg-info/SOURCES.txt'
2023-09-18T18:51:11,540   adding license file 'LICENSE'
2023-09-18T18:51:11,540   adding license file 'AUTHORS.rst'
2023-09-18T18:51:11,543   writing manifest file '/tmp/pip-pip-egg-info-87lpi6um/openupgradelib.egg-info/SOURCES.txt'
2023-09-18T18:51:11,582   Preparing metadata (setup.py): finished with status 'done'
2023-09-18T18:51:11,584   Source in /tmp/pip-req-build-f8can7w8 has version 3.4.2.dev67+gd0aee90, which satisfies requirement openupgradelib==3.4.2.dev67+gd0aee90 from git+https://github.com/OCA/openupgradelib/@master (from -r /home/odoo/.requirements.txt (line 7))
2023-09-18T18:51:11,584   Removed openupgradelib==3.4.2.dev67+gd0aee90 from git+https://github.com/OCA/openupgradelib/@master (from -r /home/odoo/.requirements.txt (line 7)) from build tracker '/tmp/pip-build-tracker-ymkimtw4'
2023-09-18T18:51:11,584 Requirement already satisfied: html2text in /usr/lib/python3/dist-packages (from -r /home/odoo/.requirements.txt (line 1)) (2020.1.16)
2023-09-18T18:51:11,585 1 location(s) to search for versions of suds-jurko:
2023-09-18T18:51:11,585 * https://pypi.org/simple/suds-jurko/
2023-09-18T18:51:11,585 Fetching project page and analyzing links: https://pypi.org/simple/suds-jurko/
2023-09-18T18:51:11,585 Getting page https://pypi.org/simple/suds-jurko/
2023-09-18T18:51:11,586 Found index url https://pypi.org/simple/
2023-09-18T18:51:11,741 Fetched page https://pypi.org/simple/suds-jurko/ as application/vnd.pypi.simple.v1+json
2023-09-18T18:51:11,742   Found link https://files.pythonhosted.org/packages/22/4a/7191c3d885328ede39d1934c2169c68fe53a3e3b4586ad52f328acce1d23/suds-jurko-0.4.1.jurko.1.tar.bz2 (from https://pypi.org/simple/suds-jurko/), version: 0.4.1.jurko.1
2023-09-18T18:51:11,743   Found link https://files.pythonhosted.org/packages/07/bd/474f03dc82b267db152cfb1754dfd05788058dd3aa39a3ff75a41aa7b9a1/suds-jurko-0.4.1.jurko.1.zip (from https://pypi.org/simple/suds-jurko/), version: 0.4.1.jurko.1
2023-09-18T18:51:11,743   Found link https://files.pythonhosted.org/packages/45/8d/8bd775d12c816e84ef58cd6ab46dad089e3109973cbd5e7d5747cf623a21/suds-jurko-0.4.1.jurko.2.tar.bz2 (from https://pypi.org/simple/suds-jurko/), version: 0.4.1.jurko.2
2023-09-18T18:51:11,743   Found link https://files.pythonhosted.org/packages/85/86/81f0cc58791c9d05bac4d5a0e4986ce6cb383adf59e8d205c44688923f17/suds-jurko-0.4.1.jurko.2.zip (from https://pypi.org/simple/suds-jurko/), version: 0.4.1.jurko.2
2023-09-18T18:51:11,743   Found link https://files.pythonhosted.org/packages/2a/59/d67501271712b65e1980f937b87b2ae58689fb489ec5028fafc6bf988f2c/suds-jurko-0.4.1.jurko.3.tar.bz2 (from https://pypi.org/simple/suds-jurko/), version: 0.4.1.jurko.3
2023-09-18T18:51:11,743   Found link https://files.pythonhosted.org/packages/33/0e/8ec969f0429bd1840b037455cd9367133bda9b5c8ae48f723e826fe1d212/suds-jurko-0.4.1.jurko.3.zip (from https://pypi.org/simple/suds-jurko/), version: 0.4.1.jurko.3
2023-09-18T18:51:11,744   Found link https://files.pythonhosted.org/packages/00/2e/a997b43cacac5f887fabfefd3b12598898a075a8f80bd866122c515dbb29/suds-jurko-0.4.1.jurko.4.tar.bz2 (from https://pypi.org/simple/suds-jurko/), version: 0.4.1.jurko.4
2023-09-18T18:51:11,744   Found link https://files.pythonhosted.org/packages/03/40/9b5157c24b80dc2be860f0404d6801bbb013bdcf8c689c4022f84dda91b1/suds-jurko-0.4.1.jurko.4.zip (from https://pypi.org/simple/suds-jurko/), version: 0.4.1.jurko.4
2023-09-18T18:51:11,744   Found link https://files.pythonhosted.org/packages/b7/85/bee13b11f8b7cde51a03fa1342323648318362c8bd37be50816cf890aa68/suds-jurko-0.4.1.jurko.5.tar.bz2 (from https://pypi.org/simple/suds-jurko/), version: 0.4.1.jurko.5
2023-09-18T18:51:11,744   Found link https://files.pythonhosted.org/packages/f9/67/7314f77a002cdb31e1c52b3f6efef8259f82b18ee1f046fef091381f0344/suds-jurko-0.4.1.jurko.5.zip (from https://pypi.org/simple/suds-jurko/), version: 0.4.1.jurko.5
2023-09-18T18:51:11,744   Found link https://files.pythonhosted.org/packages/40/cc/2fad53352898ebfef8b11e4b6b0ef0fac0ee8162c735db28c558d511039c/suds-jurko-0.5.tar.bz2 (from https://pypi.org/simple/suds-jurko/), version: 0.5
2023-09-18T18:51:11,744   Found link https://files.pythonhosted.org/packages/72/22/13c6ff1e731880523ceb7d6137b9450f7cca5b4bee8411017bad23af226c/suds-jurko-0.5.zip (from https://pypi.org/simple/suds-jurko/), version: 0.5
2023-09-18T18:51:11,745   Found link https://files.pythonhosted.org/packages/bd/6f/54fbf0999a606680d27c69b1ad12dfff62768ecb9fe48524cebda6eb4423/suds-jurko-0.6.tar.bz2 (from https://pypi.org/simple/suds-jurko/), version: 0.6
2023-09-18T18:51:11,745 Found link https://files.pythonhosted.org/packages/d0/88/f3bed9b494e0dae26bd55e5f3d527b8244208125024727267e8109956a11/suds-jurko-0.6.zip (from https://pypi.org/simple/suds-jurko/), version: 0.6
2023-09-18T18:51:11,745 Skipping link: not a file: https://pypi.org/simple/suds-jurko/
2023-09-18T18:51:11,754 Given no hashes to check 4 links for project 'suds-jurko': discarding no candidates
2023-09-18T18:51:11,763 Collecting suds-jurko (from -r /home/odoo/.requirements.txt (line 2))
2023-09-18T18:51:11,764   Created temporary directory: /tmp/pip-unpack-8kj54zrg
2023-09-18T18:51:11,921   Downloading suds-jurko-0.6.zip (255 kB)
2023-09-18T18:51:12,015   Added suds-jurko from https://files.pythonhosted.org/packages/d0/88/f3bed9b494e0dae26bd55e5f3d527b8244208125024727267e8109956a11/suds-jurko-0.6.zip (from -r /home/odoo/.requirements.txt (line 2)) to build tracker '/tmp/pip-build-tracker-ymkimtw4'
2023-09-18T18:51:12,015   Running setup.py (path:/tmp/pip-install-cdo5mku5/suds-jurko_7129563e6d524a7dbe9391417870a104/setup.py) egg_info for package suds-jurko
2023-09-18T18:51:12,016   Created temporary directory: /tmp/pip-pip-egg-info-12boz1l_
2023-09-18T18:51:12,016   Preparing metadata (setup.py): started
2023-09-18T18:51:12,016   Running command python setup.py egg_info
2023-09-18T18:51:12,411   error in suds-jurko setup command: use_2to3 is invalid.
2023-09-18T18:51:12,462   ERROR: [present-rich] python setup.py egg_info exited with 1
2023-09-18T18:51:12,469   [bold magenta]full command[/]: [blue]/usr/bin/python3 -c '
2023-09-18T18:51:12,469   exec(compile('"'"''"'"''"'"'
2023-09-18T18:51:12,469   # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
2023-09-18T18:51:12,469   #
2023-09-18T18:51:12,469   # - It imports setuptools before invoking setup.py, to enable projects that directly
2023-09-18T18:51:12,469   #   import from `distutils.core` to work with newer packaging standards.
2023-09-18T18:51:12,469   # - It provides a clear error message when setuptools is not installed.
2023-09-18T18:51:12,469   # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
2023-09-18T18:51:12,469   #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
2023-09-18T18:51:12,469   #     manifest_maker: standard file '"'"'-c'"'"' not found".
2023-09-18T18:51:12,469   # - It generates a shim setup.py, for handling setup.cfg-only projects.
2023-09-18T18:51:12,469   import os, sys, tokenize
2023-09-18T18:51:12,469   
2023-09-18T18:51:12,469   try:
2023-09-18T18:51:12,469       import setuptools
2023-09-18T18:51:12,469   except ImportError as error:
2023-09-18T18:51:12,469       print(
2023-09-18T18:51:12,469           "ERROR: Can not execute `setup.py` since setuptools is not available in "
2023-09-18T18:51:12,469           "the build environment.",
2023-09-18T18:51:12,469           file=sys.stderr,
2023-09-18T18:51:12,469       )
2023-09-18T18:51:12,469       sys.exit(1)
2023-09-18T18:51:12,469   
2023-09-18T18:51:12,469   __file__ = %r
2023-09-18T18:51:12,469   sys.argv[0] = __file__
2023-09-18T18:51:12,469   
2023-09-18T18:51:12,469   if os.path.exists(__file__):
2023-09-18T18:51:12,469       filename = __file__
2023-09-18T18:51:12,469       with tokenize.open(__file__) as f:
2023-09-18T18:51:12,469           setup_py_code = f.read()
2023-09-18T18:51:12,469   else:
2023-09-18T18:51:12,469       filename = "<auto-generated setuptools caller>"
2023-09-18T18:51:12,469       setup_py_code = "from setuptools import setup; setup()"
2023-09-18T18:51:12,469   
2023-09-18T18:51:12,469   exec(compile(setup_py_code, filename, "exec"))
2023-09-18T18:51:12,469   '"'"''"'"''"'"' % ('"'"'/tmp/pip-install-cdo5mku5/suds-jurko_7129563e6d524a7dbe9391417870a104/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-12boz1l_[/]
2023-09-18T18:51:12,469   [bold magenta]cwd[/]: /tmp/pip-install-cdo5mku5/suds-jurko_7129563e6d524a7dbe9391417870a104/
2023-09-18T18:51:12,470   Preparing metadata (setup.py): finished with status 'error'
2023-09-18T18:51:12,470 ERROR: [present-rich] metadata generation failed
2023-09-18T18:51:12,473 Exception information:
2023-09-18T18:51:12,473 Traceback (most recent call last):
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/build/metadata_legacy.py", line 64, in generate_metadata
2023-09-18T18:51:12,473     call_subprocess(
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
2023-09-18T18:51:12,473     raise error
2023-09-18T18:51:12,473 pip._internal.exceptions.InstallationSubprocessError: python setup.py egg_info exited with 1
2023-09-18T18:51:12,473 
2023-09-18T18:51:12,473 The above exception was the direct cause of the following exception:
2023-09-18T18:51:12,473 
2023-09-18T18:51:12,473 Traceback (most recent call last):
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
2023-09-18T18:51:12,473     status = run_func(*args)
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
2023-09-18T18:51:12,473     return func(self, options, args)
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py", line 377, in run
2023-09-18T18:51:12,473     requirement_set = resolver.resolve(
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
2023-09-18T18:51:12,473     result = self._result = resolver.resolve(
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
2023-09-18T18:51:12,473     state = resolution.resolve(requirements, max_rounds=max_rounds)
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
2023-09-18T18:51:12,473     self._add_to_criteria(self.state.criteria, r, parent=None)
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
2023-09-18T18:51:12,473     if not criterion.candidates:
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
2023-09-18T18:51:12,473     return bool(self._sequence)
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
2023-09-18T18:51:12,473     return any(self)
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
2023-09-18T18:51:12,473     return (c for c in iterator if id(c) not in self._incompatible_ids)
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
2023-09-18T18:51:12,473     candidate = func()
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
2023-09-18T18:51:12,473     self._link_candidate_cache[link] = LinkCandidate(
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
2023-09-18T18:51:12,473     super().__init__(
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
2023-09-18T18:51:12,473     self.dist = self._prepare()
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
2023-09-18T18:51:12,473     dist = self._prepare_distribution()
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
2023-09-18T18:51:12,473     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 538, in prepare_linked_requirement
2023-09-18T18:51:12,473     return self._prepare_linked_requirement(req, parallel_builds)
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 653, in _prepare_linked_requirement
2023-09-18T18:51:12,473     dist = _get_prepared_distribution(
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
2023-09-18T18:51:12,473     abstract_dist.prepare_distribution_metadata(
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
2023-09-18T18:51:12,473     self.req.prepare_metadata()
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_install.py", line 568, in prepare_metadata
2023-09-18T18:51:12,473     self.metadata_directory = generate_metadata_legacy(
2023-09-18T18:51:12,473   File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/build/metadata_legacy.py", line 71, in generate_metadata
2023-09-18T18:51:12,473     raise MetadataGenerationFailed(package_details=details) from error
2023-09-18T18:51:12,473 pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
2023-09-18T18:51:12,482 Removed suds-jurko from https://files.pythonhosted.org/packages/d0/88/f3bed9b494e0dae26bd55e5f3d527b8244208125024727267e8109956a11/suds-jurko-0.6.zip (from -r /home/odoo/.requirements.txt (line 2)) from build tracker '/tmp/pip-build-tracker-ymkimtw4'
2023-09-18T18:51:12,483 Removed build tracker: '/tmp/pip-build-tracker-ymkimtw4'

Is suds-jurko==0.6 a version to enable in the SH?

**Comment by Saurat** [comment]
Python 2 convention for 'use_2to3' is not appliable anymore to python3 (on which works Odoo 16). maybe can we consider using https://pypi.org/project/zeep/ instead?

**Comment by maq-adhoc** [comment]
Hi @Saurat , There are no plans to migrate the modules to zeep. You can remove pyafip_ws from requirements.txt. In the corresponding repo.
